version: '3.8'

services:
  postgres:
    image: postgres:15.4
    container_name: social_postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5085:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
